name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Install xmllint
      run: sudo apt-get install libxml2-utils
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests
      run: make test
    # Re-enable once I am using stable locally again
    # - name: Check formatting
    #   run: cargo fmt -- --check